name: Continuous Integration

on:
  workflow_dispatch:
  push:


jobs:

  build-release:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os: [macos-12, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: swift build --disable-automatic-resolution -c release
